resolver: lts-14.0

packages:
- .

extra-deps:
- git: https://github.com/sigrlami/servant-jsonrpc
  commit: a225070b31e3c68d004800ae35eed0b7ec1b2a70
  subdirs:
    - servant-jsonrpc
    - servant-jsonrpc-client
